version: '3.8'

services:
  app:
    build: ./backend
    image: kev125/backend
    container_name: backendContainer
    ports:
      - '8000:8000'
    networks:
      - mongo_network
    depends_on:
      - mongo

  client:
    build: ./client
    image: kev125/client
    container_name: clientContainer
    ports:
      - '5000:5000'
    networks:
      - mongo_network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: kev125
      MONGO_INITDB_ROOT_PASSWORD: Rf7ebDwjS8gRHatM
    volumes:
      - database:/data/db
    networks:
      - my_network

volumes:
  database:

networks:
  my_network:
    driver: bridge