version: '3.8'

services:
  app:
    build: ./backend
    image: kev125/backend
    container_name: backendContainer
    ports:
      - '5000:5000'
    networks:
      - my_network
    depends_on:
      - mongo
    env_file:
      - ./.env

  client:
    build: ./client
    image: kev125/client
    container_name: clientContainer
    ports:
      - '3000:80'
    networks:
      - my_network
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - database:/data/db
    networks:
      - my_network

volumes:
  database:

networks:
  my_network:
    driver: bridge